config/routes.rb
Kanshabox::Application.routes.draw do
  root :to => 'homes#index'
  resources :thanks, :only => [:index, :new, :create, :destroy]
  devise_for :users
end

app/models/thank.rb
class Thank < ActiveRecord::Base
  
  belongs_to :user
  validates :what, :length => { :in => 1..20 }
  validates :message, :length => { :in => 1..140 }
  
  def self.filter(params)
    thanks = self.where('')
    if params[:date]
      date = Date.parse(params[:date])
      thanks = where(:date_at => (date.beginning_of_day)..(date.end_of_day))
    end
    thanks
  end
  
  # def to_json_with_ext
  #   {
  #     :id => self.id,
  #     :date_at => self.date_at,
  #     :what => self.what,
  #     :message => self.message,
  #     :user_id => self.user_id,
  #     # :total_count => Thank.where(:user_id => self.user_id).count,
  #     # :date_count 
  #   }.to_json
  # end
  # alias_method_chain :to_json, :ext
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username
  
  has_many :thanks
  
  validates :username, :uniqueness => { :case_sensitive => false },
                       :length     => { :in => 3..15 }, 
                       :format     => { :with => /^[a-z0-9_]+$/ }
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  def after_sign_in_path_for(resource)
    thanks_path || root_path
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end

end

app/controllers/thanks_controller.rb
# -*- encoding: utf-8 -*-
class ThanksController < ApplicationController
  before_filter :authenticate_user!
  # GET /thanks
  # GET /thanks.json
  def index
    if params[:m]
      @month = Date.parse(params[:m].concat('-01')).beginning_of_month if params[:m]
    else
      @month = Date.today.beginning_of_month
    end
    # メモした月リストを作成
    @months = current_user.thanks.group(:date_at).count
                .keys.group_by{|key,value| key.strftime('%Y-%m') }.keys.map{|d| Date.parse("#{d}-01") }.sort.reverse
    @thanks =  current_user.thanks
                 .where(:date_at => (@month.beginning_of_month)..(@month.end_of_month))
                 .order('date_at DESC')
                 .group_by{|t| t.date_at}

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /thanks/1
  # GET /thanks/1.json
  def show
    @thank = Thank.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @thank }
    end
  end

  # GET /thanks/new
  # GET /thanks/new.json
  def new
    date = Date.today
    if params[:date]
      date = DateTime.parse(params[:date])
    end
    
    @thank = Thank.new :date_at => date

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @thank }
    end
  end

  # GET /thanks/1/edit
  def edit
    @thank = Thank.find(params[:id])
  end

  # POST /thanks
  # POST /thanks.json
  def create
    @thank = current_user.thanks.build(params[:thank])

    respond_to do |format|
      if @thank.save
        format.html { redirect_to thanks_path, notice: '感謝の気持ちが増えました！' }
        format.json { render json: @thank, status: :created, location: @thank }
      else
        format.html { render action: "new" }
        format.json { render json: @thank.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /thanks/1
  # PUT /thanks/1.json
  def update
    @thank = Thank.find(params[:id])

    respond_to do |format|
      if @thank.update_attributes(params[:thank])
        format.html { redirect_to @thank, notice: 'Thank was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @thank.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thanks/1
  # DELETE /thanks/1.json
  def destroy
    @thank = Thank.find(params[:id])
    @thank.destroy

    respond_to do |format|
      format.html { redirect_to thanks_url }
      format.json { render json: @thank, status: :created }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/thanks_helper.rb
module ThanksHelper
end

app/views/homes/index.html.haml
- title '5Thanks - 感謝できることを毎日５つメモするツール'
.hero-unit
  %h1 Welcome, 5Thanks
  %p 
    5Thanksは、毎日５つの感謝できることをメモして、ポジティブに生きたい人のためのツールです。
.row
  .span9
    
    %h2 5Thanksについて
    %p
      書籍「<a href="http://www.amazon.co.jp/gp/product/4479793054/ref=as_li_ss_tl?ie=UTF8&tag=func090b-22&linkCode=as2&camp=247&creative=7399&creativeASIN=4479793054">ハーバードの人生を変える授業</a><img src="http://www.assoc-amazon.jp/e/ir?t=&l=as2&o=9&a=4479793054" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />」の中にある
    %blockquote
      ちょっとした事でもいいので、毎日感謝できることを５つ書く
    %p
      を実践するためのツールです。「<a href="http://www.amazon.co.jp/gp/product/4479793054/ref=as_li_ss_tl?ie=UTF8&tag=func090b-22&linkCode=as2&camp=247&creative=7399&creativeASIN=4479793054">ハーバードの人生を変える授業</a><img src="http://www.assoc-amazon.jp/e/ir?t=&l=as2&o=9&a=4479793054" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />」によれば、これを続けた人は人生を肯定的に評価できるようになり、幸福感が高くなり、ポジティブな気分を味わうようになったそうです。
    
    %h3 サービスの特徴
    %ol
      %li
        %b 簡単なメモ登録
        %p 
          誰、何に対して、どんな感謝をしたのか書くだけのシンプルなツールです。
          %br
          = image_tag 'capture-2.png'
      %li
        %b 振り返りやすい
        %p 
          メモは日毎に整理されて、過去のメモを読み返しやすいです。
          = image_tag 'capture-1.png'
      %li
        %b プライベートなメモ
        %p 
          感謝のメモは他の人から見られることはありません。
        
  .span7
    %h3 お知らせ
    %p
      %b 2011-09-12
      %br 「クリック募金dff」のバナーを表示するようにしました。何か良い事したいなと思った時にクリックしてみてください。
    %p
      %b 2011-09-08
      %br 5Thanksリリースしました！

    %hr
    %p これまで#{Thank.count}の感謝がメモされました
    %p #{User.count}人が5Thanksを利用しています。
    %p
      = link_to 'ユーザー登録して感謝の気持ちをメモし始める', new_user_registration_path, :class => 'btn primary xlarge'
        
    .share
      <a href="http://b.hatena.ne.jp/entry/#{root_url}" class="hatena-bookmark-button" data-hatena-bookmark-title="5Thanks - 毎日5つの感謝をメモするサービス" data-hatena-bookmark-layout="standard" title="このエントリーをはてなブックマークに追加"><img src="http://b.st-hatena.com/images/entry-button/button-only.gif" alt="このエントリーをはてなブックマークに追加" width="20" height="20" style="border: none;" /></a><script type="text/javascript" src="http://b.st-hatena.com/js/bookmark_button.js" charset="utf-8" async="async"></script>
      <a href="http://twitter.com/share" class="twitter-share-button" data-count="horizontal" data-via="func09" data-lang="ja">ツイート</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
      <iframe src="http://www.facebook.com/plugins/like.php?app_id=172862122787841&amp;href=#{URI.encode(root_url)}send=false&amp;layout=button_count&amp;width=100&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:140px; height:21px;" allowTransparency="true"></iframe>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      = yield(:title) || "5Thanks"
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}/
    = stylesheet_link_tag 'http://twitter.github.com/bootstrap/assets/css/bootstrap-1.2.0.min.css'
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tag
    = yield(:head)
    - if Rails.env.production?
      :javascript
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-845066-11']);
        _gaq.push(['_trackPageview']);

        (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
  %body(class='#{controller_name}-#{action_name}-page')
    
    .topbar
      .fill
        .container
          %h3
            %a(href='/')
              5Thanks
          - if user_signed_in?
            %ul
              %li= link_to 'あなたの感謝', thanks_path
              %li= link_to '新しい感謝', new_thank_path
            %ul.nav.secondary-nav
              %li= link_to '設定', edit_user_registration_path
              %li= link_to 'ログアウト', destroy_user_session_path, :method => :delete
          - else
            %ul.nav.secondary-nav
              %li= link_to '新規登録', new_user_registration_path
              %li= link_to 'ログイン', new_user_session_path
    
    .container(style='margin-top: 40px; padding-top: 10px')
      - flash.each do |name, msg|
        .alert-message.small(class='#{name}')= msg
    
    .container
      .pageContent
        = yield
    
    .container.footer
      Powered by <a href='http://heroku.com'>Heroku</a>, <a href='http://rubyonrails.org/'>Rails3.1</a>, <a href='http://twitter.github.com/bootstrap/'>Twitter Bootstrap</a>
      Create by <a href='http://twitter.com/func09'>@func09</a>. <a href='http://github.com/func09/5thanks'>Github</a>

:javascript
  if($('.alert-message.small').is(':visible')){
    setTimeout(function(){
      $('.alert-message.small').fadeOut()
    }, 3000);
  }

app/views/thanks/_form.html.haml
= form_for @thank do |f|
  -if @thank.errors.any?
    .alert-message.block-message.error
      %h3= "#{pluralize(@thank.errors.count, "つのエラー")}のため保存できませんでした。"
      %ul
        - @thank.errors.full_messages.each do |msg|
          %li= msg
  
  .fieldset
    .clearfix
      %label 誰 or 何に？
      .input
        = f.text_field :what
        へ
        .help-block 例：両親、子ども、先生、友人、お天気、音楽 etc
    .clearfix
      %label 感謝の言葉
      .input
        = f.text_area :message, :size => '70x2', :class => 'xxlarge'
        .help-block 
          自分の人生でありがたいと思うことはなんですか？
          %br
          書きながら思い浮かべてみよう。
    .clearfix(style='display:none;')
      %label いつの感謝？
      .input
        = f.date_select :date_at
    .clearfix
      .input
        = f.submit '感謝をメモする', :class => 'btn primary'

app/views/thanks/edit.html.haml
%h1 Editing thank

= render 'form'

= link_to 'Show', @thank
\|
= link_to 'Back', thanks_path

app/views/thanks/index.html.haml
- if @month.this_month?
  - title "今月のあなたの感謝の言葉 - 5Thanks"
- else
  - title "#{@month.strftime("%Y年%m月")}のあなたの感謝の言葉 - 5Thanks"

.page-header
  %h1
    - if @month.this_month?
      今月のあなたの感謝の言葉
    - else
      #{@month.strftime("%Y年%m月")}のあなたの感謝の言葉
  %p
    - unless current_user.thanks.count == 0
      あなたは今日までに<b>#{current_user.thanks.count}個</b>の感謝メモを残しました

.row
  .span10
    - unless @thanks.count > 0
      %p.empty-message
        - if @month.end_of_month.future?
          今月はまだ感謝メモをつけていません。
          %br
          = link_to "さぁ、感謝できることをメモしましょう！", new_thank_path
        - else
          この月は感謝メモがありませんでした
    - else
      %dl
        - if @month.this_month? and not @thanks.keys.first.today?
          - @thanks[Date.today] = []
        - for date in @thanks.keys.sort.reverse
          - thanks = @thanks[date]
          %dt.date(data-date='#{date.strftime("%Y-%m-%d")}')
            %span.count
              %span.num= thanks.count
              %span.label thx
            - if date.today?
              - label_when = "今日"
              %time(datetime='') 今日
            - else
              - label_when = "この日"
              %time(datetime='#{date.strftime("%Y-%m-%d")}')= date.strftime("%Y/%m/%d")
          %dd.thanks(data-date='#{date.strftime("%Y-%m-%d")}')
            %ol
              - for thank in thanks
                %li(data-thank-id='#{thank.id}')
                  %b= "#{thank.what}へ"
                  %span.destroy(style='display:none;')
                    = link_to 'x', thank_path(thank,:format => :json), :remote => true, :class => 'btn-destroy', :method => :delete
                  %br
                  %p.message= thank.message
            .system-message
              - if date.today?
                %p.empty-thanks-message(style='display:none;')
                  今日はまだ感謝をメモしてないよ。
                  = link_to "ちょっとした事でいいんだよ", new_thank_path
                %p.full-thanks-message(style='display:none;')
                  今日もいっぱい良いことがあったね！
                  = link_to "もっと感謝したことはある？", new_thank_path
                %p.notyet-thanks-message(style='display:none;')
                  今日はあと<span class='num'>#{5-thanks.size}</span>個の感謝をメモろう。
                  = link_to "あとちょっと！", new_thank_path
              - else
                %p.full-thanks-message(style='display:none;')
                  いっぱい良いことがあったね！
                  = link_to "もっと感謝したいことはある？", new_thank_path(:date => date.strftime("%Y%m%d"))
                %p.notyet-thanks-message(style='display:none;')
                  もう少し感謝のメモを書こう。
                  = link_to "思い出してみて！", new_thank_path(:date => date.strftime("%Y%m%d"))
  .span6
    %p
      <a href="http://www.dff.jp" target="_blank"><img src="http://bnr.dff.jp/pix/dffbanner200909_01_171x70.gif" alt="クリックで救える命がある。" width="171" height="70" border="0"></a>
    %ul
      - for date in @months
        %li
          = link_to date.strftime('%Y年%m月'), thanks_path(:m => date.strftime('%Y-%m'))
  
          
          
          
          
          
          
          

app/views/thanks/new.html.haml
- title '感謝の気持ちをメモする - 5Thanks'

.page-header
  %h1
    感謝の気持ちをメモする

.row
  .span16
    = render 'form'

app/views/thanks/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_thank_path(@thank)
\|
= link_to 'Back', thanks_path